apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: express-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      role: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
